### PR TITLE
Add color variable to specify color from input and select

### PR DESCRIPTION
**Pull request by marvinhuebner**
First of all many thanks for the small but useful library. 

My changes adds the options for an input or select to define a color.

I didn't recompile the files, so the changes are just made in the source.

I'm looking forward to your feedback.

### CODE REVIEW

**Comment by electerious** [comment]
Thanks for the PR!

Is `caret-color: $formbase__color;` required? It looks like most browsers are using `color` for the caret color.

Two changes are required to finish this PR:

- `. control` should also get the color
- The variable should be added to the options in the readme

**Comment by marvinhuebner** [comment]
You seem right. I've removed `caret-color` and integrated the requested changes.

**Comment by electerious** [comment]
Looks good! Will test and merge it by time 👍

**Comment by marvinhuebner** [comment]
Cool. Thanks!

**Comment by electerious** [comment]
Merged an part of v8 :)

**Pull request merged**
